### ISSUE TITLE
Jenkins 2.0

### ISSUE THREAD

**Issue by himadrisingh001** [jenkinsci/google-oauth-plugin#10]
I'm not able to get credentials options for p12 key in Jenkins 2.0 though it works fine with older one.

**Comment by jekkel** [comment]
Same here.
* Jenkins ver. 2.132
* Google OAuth Credentials Plugin 0.6

See screenshot (sorry for being in german)
![missing-google-credential-types](https://user-images.githubusercontent.com/701091/42929051-3cbab98c-8b39-11e8-9986-2678b317946f.png)

Any other information we can give?
