### ISSUE TITLE
Security Vulnerability.

### ISSUE THREAD

**Issue by johnhamelink** [jenkinsci/google-oauth-plugin#11]
Snapchat have experienced a security vulnerability relating to this plugin:

https://hackerone.com/reports/231460

I was alerted to this by a security researcher who was able to demonstrate to me that he was able to log in to our Jenkins instance.

I've removed this plugin for now, as we were not using it, but this should be fixed very soon - or at least removed from Jenkins' plugin database.

**Comment by mattmoor** [comment]
This plugin doesn't deal with login, do you mean: https://github.com/jenkinsci/google-login-plugin ?

**Comment by johnhamelink** [comment]
@mattmoor - in all honesty I removed all plugins which touched google. It could well have been the google-login-plugin. It would be worth having someone from Snapchat to disclose the issue to a Jenkins contributor so that it can be fixed.

**Comment by orrc** [comment]
It may well be that @daniel-beck and the security team already know about this, but if not, there's a defined reporting procedure for security issues: https://jenkins.io/security/#reporting-vulnerabilities

**Comment by daniel-beck** [comment]
@johnhamelink Please report the issue as described on https://jenkins.io/security/#reporting-vulnerabilities with as many details as possible (e.g. names and versions of affected plugins, even if now disabled, would be important). Thank you.

**Comment by johnhamelink** [comment]
@daniel-beck no problem, I will do this now!

**Comment by mattmoor** [comment]
I reached out to Snap.  They indicated that the vulnerability was not in this plugin, but in their infrastructure code.

@daniel-beck I'm no longer an owner, so I can't close this, can you?

**Comment by daniel-beck** [comment]
FTR the issue that @johnhamelink experienced was a wrong configuration issue, also unrelated to this plugin.
