### ISSUE TITLE
The Google Service Account credential `X` has not been configured correctly.

### ISSUE THREAD

**Issue by JokerDen** [jenkinsci/google-oauth-plugin#14]
I has next error:
`The Google Service Account credential `X` has not been configured correctly.`
I found on [stackoverflow](https://stackoverflow.com/questions/34703479/gerrit-googleplay-publisher-plugin-credentials-has-not-been-configured-correctly) that it possible to fix by switching from version 0.4 to 0.3. But I'm already using version 0.5 and generally don't have option to downgrade version.

I'm using local instance of Jenkins it it's matter.

**Comment by nikarul** [comment]
I'm having this same issue, even after updating to 0.6, on our local Jenkins server.

**Comment by JokerDen** [comment]
As an option you can try to remove special symbols from password or escape them.

**Comment by gwynjudd** [comment]
>As an option you can try to remove special symbols from password or escape them.

@JokerDen what does this mean? I'm tearing my hair out trying to come up with a workable solution. Which password are you referring to here?

**Comment by juliancadi** [comment]
@gwynjudd could you confirm that this is indeed a password issue?

**Comment by gwynjudd** [comment]
@juliancadi no I don't know what the issue is

**Comment by stephenashank** [comment]
This should work now with versions 0.8 and above. Feel free to reopen if you still encounter issues.
