### ISSUE TITLE
Transfer project ownership: Cloud Graphite: Platforms

### ISSUE THREAD

**Issue by craigatgoogle** [jenkinsci/google-oauth-plugin#27]
The GCP Cloud Graphite: Platforms team would like to adopt the Google OAuth Plugin so that we can take over support and provide future engineering investment into the project.

Plugin Repo: https://github.com/jenkinsci/google-oauth-plugin
Github username: https://github.com/craigatgoogle

**Comment by astroilov** [comment]
I'm Andrey Stroilov and I approve this action.
