### ISSUE TITLE
 Unable to load google cloud credentials from json file

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-oauth-plugin#33]
Hello, 

It seems Jenkins is unable to load my credentials from the JSON credentials file generated from google cloud storage. I get an exception AccountIdNotSetException which apparently is supposed to be the "client_email" property in the JSON config file, however it's present and set, but the exception is still raised. I have attached  screenshots detailing my scenario. I am using the Google Cloud Storage plugin.

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-48796

**Comment by stephenashank** [comment]
Made obsolete by #19 and #48. Use secretJsonKey to provide the secret bytes directly.
