### ISSUE TITLE
credentials plugin does not save json file for google play publishing

### ISSUE THREAD

**Issue by craigatgoogle** [jenkinsci/google-oauth-plugin#36]
when creating a credential for google play publishing, the credentials plugin 2.1.13, will not save the json file that I am trying to upload to it.  uploading seems to work as I have added some plugins manually by uploading the hpi files.

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-45660

**Comment by n0minal** [comment]
This issue still happening to me, I'm using latest version of jenkins and all of my plugins are up to date

**Comment by n0minal** [comment]
The issue was fixed on latest update and works just fine now.

**Comment by stephenashank** [comment]
Great to hear, thanks for following up.
