### ISSUE TITLE
Credential creation via the API

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-oauth-plugin#39]
Would be (or is it already) possible to create Google OAuth credentials via the Credential API?

If this is possible, one could then use automation tools for provisioning jenkins and passing through the Google Cloud JSON key files

Supporting examples of people attempting to use the credentials REST API:

https://github.com/arangamani/jenkins_api_client/issues/162

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-35398
