### ISSUE TITLE
Google OAuth plugin should reaffirm auth on refresh

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-oauth-plugin#40]
The access token provided by OAuth expires after a very short amount of time, but the acceptance is still cached, and simply clicking Login will reaffirm that acceptance and regenerate the auth token (and not present the full OAuth handshake). Rather than forcing the user to periodically click "Log In", the plugin should check that the access token is valid before the page render (and, if it already does that and is just reacting to short-lived access tokens, use a refresh token to acquire a new access token if the access token is no longer valid)

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-34609

**Comment by stephenashank** [comment]
If a plugin incorporates this plugin, it is their responsibility to refresh the tokens provided. Here is an example: https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/develop/src/main/java/com/google/jenkins/plugins/k8sengine/CredentialsUtil.java#L129
