### ISSUE TITLE
p12 path not saving in credentials.xml

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-oauth-plugin#41]
.p12 file not recordings in credentials.xml and empty(has size 0 bytes (placed in folder \gauth))

Steps to reproduce:
1) install google-oauth-plugin
2) go to Jenkins Dashboard
3) login as Administrator
4) go to Credentials
5) Select "Global credentials (unrestricted)"
6) Select "Add Credentials"
7) Kind - Google Service account from private key
8) Provide any "Project Name"
9) Select option "P12 key"
10) Fill "E-Mail Address"
11) provide p12 key
12) press "ok"
13) Look into credentials.xml in Jenkins home folder

e-mail for project filled, but no path to p12 key
14) Check size of p12 key in folder "gauth"
size of p12 key is 0 bytes
On Jenkins installed in Debian 8 by deb file all works fine.

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-31638

**Comment by stephenashank** [comment]
Made obsolete by #19 and #48. Keyfiles are no longer stored directly, the Jenkins credentials store holds the secret after uploading the keyfile.
