### ISSUE TITLE
[Code Cleanup]: Remove use of unsupported FindBugs tool

### ISSUE THREAD

**Issue by craigatgoogle** [jenkinsci/google-oauth-plugin#49]
FindBugs is no longer maintained. We should re-factor the code to no longer depend upon it. At a glance it appears the primary use case throughout the code is with the @CheckNull annotation. This can be replaced with use of java.util.Optional throughout.

**Comment by stephenashank** [comment]
Resolved with release 0.8. The supported spotbugs tool from the parent pom takes its place so there is no need to change the use of @CheckNull.
