### ISSUE TITLE
Can't find Credential by ID at Folder level

### ISSUE THREAD

**Issue by adriavernetta** [jenkinsci/google-oauth-plugin#87]
Hello!

We've been testing the Android publishing plugin, built on top of this one, and we're experiencing problems because it's unable to find any Folder level Credential when using GoogleRobotCredentials's getByID.
This is because the Jenkins instance is being passed for the lookup in _CredentialsProvider.lookupCredentials(GoogleRobotCredentials.class, Jenkins.get(), ACL.SYSTEM, Collections.emptyList());_ which makes it only check on System credentials.

If the item passed was the current execution context, it would look from Folder and up its parents. Is this something that's planned to be adapted? Otherwise it's impossible to use Folder-level credentials. In our systems most credentials are folder dependent (as there's many folders and stakeholders using the same central system).

**Comment by orrc** [comment]
Yeah, that's exactly the problem.

For now, I fixed it in the Google Play Android Publisher Plugin here by adapting those methods, and using the current context:
https://github.com/jenkinsci/google-play-android-publisher-plugin/pull/27

**Comment by adriavernetta** [comment]
Nice! Thanks for the fix!

**Comment by orrc** [comment]
This should probably still be fixed in this plugin, but it's likely not too urgent; it doesn't look like [any other (public) plugins](https://github.com/search?q=org%3Ajenkinsci+googlerobotcredentials.getCredentialsListBox&type=Code) use those convenience methods.
